### ISSUE TITLE
zksync ethers6 BrowserProvider cannot execute the paymaster properly

### ISSUE THREAD

**Issue by chongqiangchen** [zksync-sdk/zksync-ethers#100]
#### 📝 Description

Provide a clear and concise description of the bug.
I used technology nextjs + web3modal + ethers6 + zksync-ethers6 to build, But I'm trying to will have a contract here, https://docs.zksync.io/build/tutorials/smart-contract-development/paymasters/custom-paymaster-tutorial.htm l When applying to the page, I found that I could not call normally, I made several attempts:
1. ethers5 + zksync-ethers5 works properly
2. Directly use the private key to build the wallet call, it can work normally
3. ethers6 + zksync-ethers6 + window.ethereum, does not work properly

#### 🔄 Reproduction Steps

1. demo: https://github.com/chongqiangchen/zksync-nft-demo/blob/1bf9455add33f8e7e4b80aea99a8f13461d59741/hooks/use-token.ts#L19
2. checkout v6 branch
3. pnpm install && pnpm dev
4. mint token and mint token again

#### 🤔 Expected Behavior

Describe what you expected to happen.

#### 😯 Current Behavior

Describe what actually happened.

#### 🖥️ Environment

- **Node version**: [e.g., Node 18.16.1]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:
- zkSync Sepolia Testnet
- **PAYMASTER_ADDRESS** = 0xBC94cCE2637a72F888962A9Ba12E03B50a92470C
- **TOKEN_ADDRESS** = 0x8Bb089cF2aaE59f7404391b8CE5Db6417E99066b
- **NFT_ADDRESS** = 0xD7761373119F61135b1EfD5f421F0134135E1871

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by danijelTxFusion** [comment]
@chongqiangchen Have you managed to solve this problem? I was trying to reproduce the error, and it seems the issue is due to an invalid address being set as the transaction's `from` field: `invalid sender. can't start a transaction from a non-account`. Please ensure that gas estimation only accepts an externally owned account (EOA) for the `from` field. That error produced the following error:

```
missing revert data (action="estimateGas", data=null, reason=null, transaction={ "data": "0x40c10f1900000000000000000000000016939aa8e0a7e27d0c5314701d76c3bd68c3a94600000000000000000000000000000000000000000000003635c9adc5dea00000", "to": "0x8Bb089cF2aaE59f7404391b8CE5Db6417E99066b" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.11.1)
```

![error](https://github.com/zksync-sdk/zksync-ethers/assets/129277218/abf9f635-3be2-42bd-9e14-9e0f0e574f38)

**Comment by chongqiangchen** [comment]
> @chongqiangchen Have you managed to solve this problem? I was trying to reproduce the error, and it seems the issue is due to an invalid address being set as the transaction's `from` field: `invalid sender. can't start a transaction from a non-account`. Please ensure that gas estimation only accepts an externally owned account (EOA) for the `from` field. That error produced the following error:
> 
> ```
> missing revert data (action="estimateGas", data=null, reason=null, transaction={ "data": "0x40c10f1900000000000000000000000016939aa8e0a7e27d0c5314701d76c3bd68c3a94600000000000000000000000000000000000000000000003635c9adc5dea00000", "to": "0x8Bb089cF2aaE59f7404391b8CE5Db6417E99066b" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.11.1)
> ```
> 
> ![error](https://private-user-images.githubusercontent.com/129277218/331373255-abf9f635-3be2-42bd-9e14-9e0f0e574f38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyOTI1OTYsIm5iZiI6MTcxNzI5MjI5NiwicGF0aCI6Ii8xMjkyNzcyMTgvMzMxMzczMjU1LWFiZjlmNjM1LTNiZTItNDJiZC05ZTE0LTllMGYwZTU3NGYzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQwMTM4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjMxZjhjZGExNGEzMjhmZTBjZmVkMDJmYjZhMmE2ZGY5ODY5NjkyNzJhZDE4NmU5MGIzMGE3ODIwODUwNGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x3KLiBUznRgzfz_S6C0-SSttzrfpROY3msb2DBHmpvc)

Sorry, I just saw it, I'll check it later ~
