### ISSUE TITLE
estimateDefaultBridgeDepositL2Gas documentation inconsistent with implementation

### ISSUE THREAD

**Issue by FaCRO** [zksync-sdk/zksync-ethers#197]
#### 📝 Description

The `estimateDefaultBridgeDepositL2Gas` function ([function definition](https://github.com/zksync-sdk/zksync-ethers/blob/8b39a42854ffd0b53a8c298dcc5408ec1bbfb40f/src/utils.ts#L1342)) accepts an `amount` argument.
The documentation for this argument states ` * @param amount The deposit amount.`. However looking at the actual implmentation of `estimateDefaultBridgeDepositL2Gas` we see the following call to `estimateL1ToL2Execute` ([function definition](https://github.com/zksync-sdk/zksync-ethers/blob/8b39a42854ffd0b53a8c298dcc5408ec1bbfb40f/src/provider.ts#L1104))

```
return await providerL2.estimateL1ToL2Execute({
      contractAddress: to,
      gasPerPubdataByte: gasPerPubdataByte,
      caller: from,
      calldata: '0x',
      l2Value: amount,
    });
 ```

In the `estimateL1ToL2Execute` documentation `l2Value` is described as ` * @param [transaction.l2Value] The current L2 gas value.`.

Which seems to contradict the use of this field as the deposit amount. 

As a result, a bridge interface that uses the documented way to estimate L2 gas price, will receive a different L2 gas amount, depending on token input amount - which from my understanding makes no sense.

IMO the documentation `estimateDefaultBridgeDepositL2Gas` needs to be updated. To my understanding, instead of the deposit amount - the caller has to provide the current L2 gas value.

#### 🔄 Reproduction Steps

Implement the call as `estimateDefaultBridgeDepositL2Gas` and execute with varying `amount`.

#### 🤔 Expected Behavior

All else being equal, the estimated gas price should not change if the caller is intending to bridge more or less tokens.

#### 😯 Current Behavior

The estimate L2 gas price on deposit changes with the deposit amount.

**Comment by petarTxFusion** [comment]
Thanks for reaching out, this is the issue with the docs. The `l2Value` is not the current l2 gas value, we will change it in the docs and we will also change the parameter name to amount in some future release since that would be breaking change.
