### ISSUE TITLE
Upgrading `zksync-ethers` to `6.12.0` breaks hardhat chai matchers

### ISSUE THREAD

**Issue by mmv08** [zksync-sdk/zksync-ethers#200]
#### 📝 Description
The following assertion:
```
            await expect(accessor.simulate(tx.to, tx.value, tx.data, tx.operation)).to.be.revertedWith(
                "SimulateTxAccessor should only be called via delegatecall",
            );
```

fails with zksync-ethers 6.12.0 with
```
  1) SimulateTxAccessor
       estimate
         should enforce delegatecall:
     Error: execution reverted: SimulateTxAccessor should only be called via delegatecall (transaction={ "data": "0x1c5fb211000000000000000000000000915148c3a7d97ecf4f741ffaab8263f9d66f2d0c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044484560b2000000000000000000000000e2b8cb53a43a56d4d2ab6131c81bd76b86d3afe5000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0xe2b8cb53a43a56d4d2ab6131c81bd76b86d3afe5", "to": "0x2bec1716df0f0790703f57695649a80cc1b6b119" }, info={ "_error": { "error": { "code": 3, "data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003953696d756c61746554784163636573736f722073686f756c64206f6e6c792062652063616c6c6564207669612064656c656761746563616c6c00000000000000", "message": "execution reverted: SimulateTxAccessor should only be called via delegatecall" }, "id": 204, "jsonrpc": "2.0" }, "payload": { "id": 204, "jsonrpc": "2.0", "method": "zks_estimateFee", "params": [ { "data": "0x1c5fb211000000000000000000000000915148c3a7d97ecf4f741ffaab8263f9d66f2d0c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044484560b2000000000000000000000000e2b8cb53a43a56d4d2ab6131c81bd76b86d3afe5000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0xe2b8cb53a43a56d4d2ab6131c81bd76b86d3afe5", "to": "0x2bec1716df0f0790703f57695649a80cc1b6b119" } ] } }, code=3, version=6.13.2)
      at makeError (node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at HardhatZksyncEthersProvider.getRpcError (node_modules/zksync-ethers/src/provider.ts:2390:21)
      at /Users/mmv/projects/safe/safe-contracts/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:563:45
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```

but works with 6.11.2

#### 🔄 Reproduction Steps

1. Clone the repo & checkout to the branch from this [PR](https://github.com/safe-global/safe-smart-account/pull/742)
2. run `npm i && npm test:zk`, observe the test suite successfully ran
3. upgrade zksync-ethers to 6.12.0 in package json
4. repeat step 2, observe the test suite failing
5. The test from the issue description can be found in `test/accessors/SimulateTxAccessor.spec.ts` 

#### 🤔 Expected Behavior

The test suite passes after the upgrade

#### 😯 Current Behavior

The test suite fails

#### 🖥️ Environment

- **Node version**: v20.11.1
- **Operating System & Version**: macOS Sonoma 14.6.1 arm64

**Comment by petarTxFusion** [comment]
We have updated how the error handling works since a lot of the custom ZKsync error messages where not displayed correctly with `ethers v6`. If I am not mistaken in your test its throwing correct error just with additional data, so could you adapt that test to check if error message contains `SimulateTxAccessor should only be called via delegatecall`?

**Comment by mmv08** [comment]
> We have updated how the error handling works since a lot of the custom ZKsync error messages where not displayed correctly with `ethers v6`. If I am not mistaken in your test its throwing correct error just with additional data, so could you adapt that test to check if error message contains `SimulateTxAccessor should only be called via delegatecall`?

The error is not from the assertion. It's coming from the `accessor.simulate(tx.to, tx.value, tx.data, tx.operation)` invocation.

If it would've been the assertion that throws, the error message would be:
```
 AssertionError: Expected transaction to be reverted with reason 'should only be called via delegatecall', but it reverted with reason 'SimulateTxAccessor should only be called via delegatecall'
 ```
 
 Also, I've been tinkering with it and I found that if i remove this overridden getRpcError method, it works again https://github.com/zksync-sdk/zksync-ethers/compare/v6.11.2...v6.12.0#diff-e0e6d91455eef50c5793e300039e5cdc7e6d372707172b639564495e4fa0a2f3R2386-R2394

**Comment by petarTxFusion** [comment]
I have found the issue, the fix should be live today or tomorrow

**Comment by mmv08** [comment]
> I have found the issue, the fix should be live today or tomorrow

Thank you!

**Comment by petarTxFusion** [comment]
It should work now with version `v6.12.1`
