### ISSUE TITLE
get UNSUPPORTED_OPERATION error

### ISSUE THREAD

**Issue by yarikMyroniuk** [zksync-sdk/zksync-ethers#75]
#### 📝 Description

Provide a clear and concise description of the bug.
When I tried to get list of prefetched transactions from the block, I get an error UNSUPPORTED_OPERATION

Error: transactions were not prefetched with block request (operation="transactionResponses()", code=UNSUPPORTED_OPERATION, version=6.11.1)
    at ZkSyncEraService.listenTransactionsToMaster (/Users/macbookpro16/Desktop/Retrobridge/backend/src/modules/zk_sync_era/services/zk_sync_era.service.ts:209:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    
  I tried to get list of prefetched txs via ethers but it didn't work, I had an error "missing r in transaction", some like missing r or v in one tx of list prefetched transactions

#### 🔄 Reproduction Steps

1. Call method provider.getBlock(block, true);
2. And when you'll want to get prefetched txs, you will get an error

#### 🤔 Expected Behavior

Describe what you expected to happen.

#### 😯 Current Behavior

Describe what actually happened.

#### 🖥️ Environment

- **Node version**: [e.g., Node 18.16.1]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by alexfilip2** [comment]
It's worth mentioning that the raw RPC call prefetches txs along with the block:
`curl https://mainnet.era.zksync.io -X POST -H "Content-Type: application/json" --data '{"method":"eth_getBlockByNumber","params":["latest",true],"id":1,"jsonrpc":"2.0"}'`

**Comment by danijelTxFusion** [comment]
@yarikMyroniuk Use `zksync-ethers` library for block fetching because `ethers` is not fully compatible with zkSync Era.

Here's an example:

```ts
import { Provider, types, utils } from "zksync-ethers";

const sepoliaProvider = Provider.getDefaultProvider(types.Network.Sepolia);
const mainnetProvider = Provider.getDefaultProvider(types.Network.Mainnet);

async function main() {
    const sepoliaBlock = await sepoliaProvider.getBlock('latest', true);
    const mainnetBlock = await mainnetProvider.getBlock('latest', true);

    console.log(`Sepolia latest block: ${utils.toJSON(sepoliaBlock)}`);
    console.log(`Mainnet latest block: ${utils.toJSON(mainnetBlock)}`);
}

main()
    .then()
    .catch((error) => {
        console.log(`Error: ${error}`);
    });
```

Output:
```
Sepolia latest block: {"_type":"Block","baseFeePerGas":"100000000","difficulty":"0","extraData":"0x","gasLimit":"4294967295","gasUsed":"682433","hash":"0x1cc59f7fb3259b3558393c1b4a4f9f9a4e0df8593e8125ff3f4ff3e0178ba3bf","miner":"0x0000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":1098924,"parentHash":"0xb76683e496acbdb8c0c993e506a7cdece6953744f625a4b647f1f524b45a57a0","timestamp":1710019813,"transactions":["0x983f34526cd7a132a98ad38f6478b3fcc6493975b5afdc42654f83b79137d253"]}
Mainnet latest block: {"_type":"Block","baseFeePerGas":"100000000","difficulty":"0","extraData":"0x","gasLimit":"4294967295","gasUsed":"10518335","hash":"0xafef3e111162b39fc25f57a0f716bafa211cbaa2bea96f5049e5a01752cd13be","miner":"0x0000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":28556805,"parentHash":"0x8fd65c0bfd7bfba717bd7d97ace711d4bb4c1693eb61c26ed8a53708fee5e3b3","timestamp":1710019819,"transactions":["0x21c8744a97451b98ea1f97be91d02922573b1a2fc3eafacfdc2fe75c760712a7","0x9ef8642ec49e4f4232d688c1a5a07fde9fdf42b31998ecacd8948c8ded48d757","0x4b54929960175c1e1b330f32a3613d0315758aa550fc54e6d36b5db3c8265736","0xc1dab8a9093b9b18ddfcbef2f54e19a6d1fe318c85f03ca1132d92b6aa24c169","0x4cb73f1777f65b5992f54e7ecdc6bdd7966ff2c9a6d536698802b9e750608f14","0xa112bda0083a7b817272b6a46e978edb5e7465a5d84e6443fa1d961cb8381ff3","0x6dd1722cb05bac4b375d33994edc416b0363d5db0c1db01d28ddd12e008896b1","0x6fa14274103c34b83604450cbf0dcbb03b28a3721b564f5ab3683497ac1619b8","0x6ee21e37e9b6608d5239b497273481a6837173ac37e24cf3776da4fb18e5002f","0x9e803ccb99765125d5bc9e8d85915382f3e661ddf475254522c77253be94ad7f","0xeddbe2c5d5eff1a628601a6e0a3f335cb8d7da2aed3afd8077cfa9b990a1bf92"]}
```

**Comment by danijelTxFusion** [comment]
This is the bug in SDK caused by incorrect creation of the `Block` object from RPC output.

```ts
const block = await mainnetProvider.getBlock('latest', true);
const txs = block.prefetchedTransactions; // throws an unsupported operation error
```

**Comment by yarikMyroniuk** [comment]
@danijelTxFusion 
So, okay, thanks
If I understand you correctly, is it an error on the side of the rpc provider?

**Comment by danijelTxFusion** [comment]
> @danijelTxFusion So, okay, thanks If I understand you correctly, is it an error on the side of the rpc provider?

It was error in SDK not parsing transaction responses correctly. Please use the `v6.6.0`  or later to avoid errors.
